version: "3.9"

services:
  photo_processor:
    build:
      context: https://github.com/BannerDuck/photo-processor.git
      dockerfile: Dockerfile
    container_name: photo_processor
    restart: unless-stopped

    # ================== Environment Variables ==================
    environment:
      TEMP_DIR: /data/temp                                # Folder where users drop images to be processed                               
      PROCESSED_DIR: /data/processed                      # Folder where 1st processed images with white background will be saved
      PROCESSED_DIR_REMBG: /data/processed_rembg          # Folder where 2nd processed images with white background will be saved
      ORIGINALS_DIR: /data/originals                      # Folder where original images are moved after processing
      LOG_FILE: /data/photo_processor.log

    # ================== Volume Mounts ==================
    volumes:
      - ./data/temp:/data/temp
      - ./data/processed:/data/processed
      - ./data/processed_rembg:/data/processed_rembg
      - ./data/originals:/data/originals
      - ./data/photo_processor.log:/data/photo_processor.log
      
