version: "3.9"
services:
  photo_processor:
    build: .
    container_name: photo_processor
    environment:
      TEMP_DIR: /data/temp
      PROCESSED_DIR: /data/processed
      PROCESSED_DIR_REMBG: /data/processed_rembg
      ORIGINALS_DIR: /data/originals
      LOG_FILE: /data/photo_processor.log
    volumes:
      - ./data/temp:/data/temp
      - ./data/processed:/data/processed
      - ./data/processed_rembg:/data/processed_rembg
      - ./data/originals:/data/originals
    restart: unless-stopped
