version: "3.9"
services:
  photo_processor:
    build: .
    container_name: photo_processor
    volumes:
      - ./data/temp:/app/temp
      - ./data/processed:/app/processed
      - ./data/processed_rembg:/app/processed_rembg
      - ./data/originals:/app/originals
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
